:global:
  componentName: rancher-monitoring
  githubUrl: https://github.com/projectsyn/component-rancher-monitoring
  feature_goldenTests: true

docs/antora.yml:
  name: rancher-monitoring
  title: rancher-monitoring

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
      - kubernetes-1.21
