:global:
  componentName: rancher-monitoring
  githubUrl: https://github.com/projectsyn/component-rancher-monitoring
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - kubernetes-1.21

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
